#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define PROJECT_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define PROJECT_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define PROJECT_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#define PROJECT_VERSION "1.0.0" //"@PROJECT_VERSION@"

#endif // APP_CONFIG_H
