name: Autobuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: Get CMake
      uses: symbitic/install-cmake@master
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'linux'
        target: 'desktop'
    - uses: actions/checkout@v4
    - name: cmake setup
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake build
      run: cmake --build build --target all -- -j4
    - uses: actions/upload-artifact@v4
      with:
        name: Linux x86_64 executable
        path: build/RetroMap
        if-no-files-found: error
        overwrite: true
  build_windows-amd64:
    runs-on: windows-latest
    steps:
    - name: Install Ninja
      run: choco install ninja
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        target: 'desktop'
    - uses: actions/checkout@v4
    - name: cmake setup
      run: cmake -S . -B build -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE=Debug
    - name: cmake build
      run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: Windows x86_64 executable
        path: build/RetroMap.exe
        if-no-files-found: error
        overwrite: true
